### ISSUE TITLE
How to get SBML identifiers in timecourse results? How to get amount/concentrations for species?

### ISSUE THREAD

**Issue by matthiaskoenig** [copasi/basico#3] opened 2021-05-05 19:29 UTC
Hi all, 
great library. I want to have timecourse results with SBML identifiers and be able to access either amount/concentration of species.

Currently there is the function
```python
def __build_result_from_ts(time_series, use_concentrations=True):
    # type: (COPASI.CTimeSeries) -> pandas.DataFrame
    col_count = time_series.getNumVariables()
    row_count = time_series.getRecordedSteps()

    column_names = []
    column_keys = []
    for i in range(col_count):
        column_keys.append(time_series.getKey(i))
        column_names.append(time_series.getTitle(i))
        # FIXME: SBML ids for comparison
        column_names.append(time_series.getSBMLId(i))

    concentrations = np.empty([row_count, col_count])
    for i in range(row_count):
        for j in range(col_count):
            if use_concentrations:
                concentrations[i, j] = time_series.getConcentrationData(i, j)
            else:
                concentrations[i, j] = time_series.getData(i, j)

    df = pd.DataFrame(data=concentrations, columns=column_names)
    df = df.set_index('Time')

    return df
```

I tried to get the SBML identifiers but need a CDataModel for that in `time_serices.getSBMLId(i)`. How would I do this? 
Is there some documention for the python-copasi API? Are there some examples and use cases?

How would I get amounts/concentrations for species?

Best Matthias

**Comment by shoops** [comment] 2021-05-05 20:42
You always have a data model. Neither model, tasks, reports, not plots can exist without it. You should be able to use
getObjectDataModel() on the time course task which created the time_series.

**Comment by fbergmann** [comment] 2021-05-06 07:09
amounts might be an issue, as copasi does not use amounts internally, so it would involve adding observable expressions of particleNumber / avogadro. I can make an example on how to do that and on how to adjust the column names to match sbml ids if that would be helpful. (the only issues here, is that sbml ids are not guaranteed to exist, they only exist if you started with an sbml file, and then not for new elements)

**Comment by matthiaskoenig** [comment] 2021-05-06 16:17
@shoops & @fbergmann Thanks for the help.
- figured out how to get the SBML ids with the dataModel. Only using SBML models, so the ids should always exist.

I could easily calculate the amounts with the compartment volumes afterwards. But I have no idea how I can get the compartments and parameters in the time course solution? Probably I have to register these somehow before simulation? Sorry, for the very naive questions.

Are there any examples for the python API which show typically tasks/workflows?

**Comment by fbergmann** [comment] 2021-05-07 10:36
Those questions are entirely alright, parameter values would automatically appear in the result of the time course if they would vary during the simulation (if they had an assignment / ode on them for example). 

I've created an example that uses the `sbml_id` wherever it is possible. I hope this works for you: 

<https://basico.readthedocs.io/en/latest/notebooks/Working_with_SBML_Ids.html>

it also adds amounts as assignment rules to the model. Let me know if this works for you

**Comment by fbergmann** [comment] 2021-11-24 10:11
closing this for now, as i believe the issue is addressed. Please feel free to reopen if needed.

**Closed as completed by fbergmann** 2021-11-24 10:11 UTC
